import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]

[font.normal]
family = "IosevkaTerm Nerd Font"

[font]
size = 13

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[window]
opacity = 0.9
