import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]

[font.normal]
family = "UbuntuMono Nerd Font"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[window]
opacity = 0.9
