name: check-formatted

on:
  push:
    paths:
      - .config/fish/*/** 
      - .config/fish/*.fish
      - .config/waybar/config.jsonc

jobs:
  check-formatted:
    runs-on: ubuntu-latest
    steps:
      - uses: fish-actions/install-fish@v1.1.0

      - uses: actions/checkout@v2

      - name: Check fish code is formatted
        run: fish_indent --check .config/fish/*/** .config/fish/*.fish

      - name: Check json code
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq empty .config/waybar/config.jsonc
